# Generated by Django 4.1.2 on 2022-10-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo_Link', models.URLField(max_length=340, verbose_name='Photo Link')),
                ('Name_of_event', models.CharField(blank=True, default=None, max_length=340, null=True, verbose_name='Name of event')),
            ],
        ),
    ]
