# Generated by Django 4.1.2 on 2022-10-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readexel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Name_of_event',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Photo_Link',
        ),
        migrations.AddField(
            model_name='book',
            name='Name of event',
            field=models.CharField(blank=True, default=None, max_length=340, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Photo Link',
            field=models.URLField(default=1, max_length=340),
            preserve_default=False,
        ),
    ]
