# Generated by Django 4.1.2 on 2022-10-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readexel', '0002_remove_book_name_of_event_remove_book_photo_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Name of event',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Photo Link',
        ),
        migrations.AddField(
            model_name='book',
            name='Name_of_event',
            field=models.CharField(blank=True, default=None, max_length=340, null=True, verbose_name='Name of event'),
        ),
        migrations.AddField(
            model_name='book',
            name='Photo_Link',
            field=models.URLField(default=1, max_length=340, verbose_name='Photo Link'),
            preserve_default=False,
        ),
    ]
